service:
  name: serverless-shop

custom:
  serverless-offline:
    port: 3000
  warmup:
    - production
    - staging

plugins:
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-plugin-warmup

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

functions:
  main:
    handler: dist/lambda-entry-point.handler
    events:
      - http:
          method: any
          path: '/'
          cors: true
      - http:
          method: any
          path: '{proxy+}'
          cors: true
